[package]
name = "axiom_mem"
version = "0.1.0"
edition = "2024"


[profile.bench]
overflow-checks = false
[profile.dev]
overflow-checks = false
[profile.release]
overflow-checks = false
[profile.test]
overflow-checks = false
